services:
  frontend:
    build:
      dockerfile: Dockerfile
      context: ./smartparking
    ports:
      - "3000:3000"
    #volumes:
    #  - ./smartparking:/app
    environment:
      - NODE_ENV=development

  node-red:
    image: nodered/node-red
    container_name: mynodered
    ports:
      - "1880:1880"
    volumes:
      - ./node-red:/data
    stdin_open: true
    tty: true

  mqtt:
    build:
      context: ./mqtt_broker
      dockerfile: Dockerfile
    ports:
      - "8000:8000"

  devices:
    build:
      context: ./devices
      dockerfile: Dockerfile
    depends_on:
      - mqtt
    environment:
      WSMQTT: ${WSMQTT:-changeme}

  postgres:
    image: postgres
    environment:
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD:-password}
      POSTGRES_USER: ${POSTGRES_USER:-postgres}
      POSTGRES_DB: ${POSTGRES_DB:-postgres}
      PGDATA: /tmp/data
    tmpfs:
      - /tmp
      - /var/run
    ports:
      - "5432:5432"
    read_only: true

  database_migrations:
    image: docker.io/migrate/migrate
    volumes:
      - ./backend/server_db/migrations:/migrations
    entrypoint: migrate -database ${DB_URL:-postgres://postgres:password@postgres:5432/postgres}?sslmode=disable -path migrations
    command: up
    read_only: true
    depends_on:
      - postgres
