services:
  frontend:
    build:
      dockerfile: Dockerfile
      context: ./smartparking
    volumes:
      - ./smartparking:/app
    network_mode: host
  node-red:
    image: nodered/node-red
    container_name: mynodered
    ports:
      - "1880:1880"
    volumes:
      - ./node-red:/data
    stdin_open: true
    tty: true
